### ISSUE TITLE
Post-initialization main function in flash.bin

### ISSUE THREAD

**Issue by madhatter88** [duck-37/dc29-badge-stuff#3]
Can you document where this begins and ends including the file offset of 0x1EB? Thank you.

**Comment by duk-37** [comment]
Don't really know what you mean. It starts at 0x1EB.
IIRC it's just main() in the source, and probably(?) the last function called by the actual entrypoint.

**Comment by madhatter88** [comment]
So I think I am misunderstanding your instructions. I found the 0x1EB offset in the flash.bin file and overwrote all the values after that with the values in target.bin. When I went to copy the UF2 file and the bin file over to the badge. It did not work. Mayne I am misunderstanding the directions, I really want to get this to work because it looks like a lot of fun!

**Comment by duk-37** [comment]
Ah, seems like I wrote 0x1E**B** in response to you; the actual offset is 0x1E**8**

**Comment by madhatter88** [comment]
how will i know if i did this correctly? I saw the badge reflash but now its just flashing red and the buttons do nothing

**Comment by duk-37** [comment]
> 
> 
> how will i know if i did this correctly? I saw the badge reflash but now its just flashing red and the buttons do nothing

Red flashing is bad. Are you using the firmware version provided from the github repo, or are you patching a version you dumped yourself? You'll need to find the file offset yourself in the second case.

**Comment by madhatter88** [comment]
I have to say thank you. I cannot say thank you enough for your responses. I flashed the one you provided over and the keys are lighting up. Top left red, top right blue, bottom left pink, bottom right yellow. When I overwrite flash.bin with the contents of target.bin. Do I overwrite 0x1E8, or do overwrite 0x1E8 and all the values after it?

**Comment by duk-37** [comment]
> 
> 
> I have to say thank you. I cannot say thank you enough for your responses. I flashed the one you provided over and the keys are lighting up. Top left red, top right blue, bottom left pink, bottom right yellow. When I overwrite flash.bin with the contents of target.bin. Do I overwrite 0x1E8, or do overwrite 0x1E8 and all the values after it?

Right, so the UF2 file provided in this repository is unmodified; once you convert it to .bin format via `uf2conv`, you'll want to *overwrite* bytes starting at 0x1E8 with the bytes from `target.bin`, and then reconvert/reflash that.

If you're still having trouble, [this fork](https://github.com/Monstriu/music-on-dc29-badge) of the repository has some makefiles and scripts that will automatically do this stuff for you. I do think this takes some of the fun out of it though ;)

**Comment by madhatter88** [comment]
I agree, the learning process for this is more appealing to me. I never had to edit a bin file (i am using ghex). I am gonna give this another shot, overwriting all of it takes a while, its a long way to get to the end of the bin file lol. This lil badge has been fun to play with :)

**Comment by duk-37** [comment]
> 
> 
> I agree, the learning process for this is more appealing to me. I never had to edit a bin file (i am using ghex). I am gonna give this another shot, overwriting all of it takes a while, its a long way to get to the end of the bin file lol. This lil badge has been fun to play with :)

Right, uh, you might want to write a quick Python script or use a different hex editor if it's taking you that long to overwrite things. You *definitely* should not be doing that manually.

**Comment by madhatter88** [comment]
lol well I am using a mouse this time. much quicker than using the trackpad like before :D. i am still getting this error when I copy it ove
![Screenshot_2021-11-11_00-24-22](https://user-images.githubusercontent.com/7418968/141242190-7a340ba2-a188-46fd-b9e4-7167b6396a1d.png)
r.

**Comment by madhatter88** [comment]
still getting a red LED :(

**Comment by duk-37** [comment]
> 
> 
> lol well I am using a mouse this time. much quicker than using the trackpad like before :D. i am still getting this error when I copy it ove ![Screenshot_2021-11-11_00-24-22](https://user-images.githubusercontent.com/7418968/141242190-7a340ba2-a188-46fd-b9e4-7167b6396a1d.png) r.

/shrug, I don't use Linux, try using sudo and the command line

> 
> 
> still getting a red LED :(

Ouch. Without a more in-depth explanation of what you're doing, I can only speculate:

1. When you dump the firmware on the device and then run it through `uf2conv`, it should tell you the start address of the firmware. If that doesn't say `0x2000`, you're going to need to modify [this define](https://github.com/duck-37/dc29-badge-stuff/blob/main/music.c#L3) to be the correct value.
2. Make absolutely sure you're *overwriting* bytes and not *inserting* them. The file size should be the exact same before and after you hex-edit in the payload.

Anyway, I'm going to head to bed for now, so I won't respond for some time after this.

**Comment by madhatter88** [comment]
So I tried copying over again, the LED is still slowly flashing re
![Screenshot_2021-11-11_14-07-03](https://user-images.githubusercontent.com/7418968/141354456-c01e7479-952d-4c04-8843-fda3748d00d0.png)
d.

**Comment by duk-37** [comment]
Exactly how many bytes are you trying to replace/overwrite?
![image](https://user-images.githubusercontent.com/74797529/141376751-387e3312-d5e8-481c-a06c-b97ccb184dc5.png)

That's a lot of bytes, I have the feeling you might be replacing too many bytes and changing the file size.

**Comment by madhatter88** [comment]
i am going to have to keep track of how many I am copying from the original file. What hex editor did you use?

**Comment by duk-37** [comment]
> 
> 
> i am going to have to keep track of how many I am copying from the original file. What hex editor did you use?

I use [HxD](https://mh-nexus.de/en/hxd/), but it's Windows only. 

You might be better of writing a quick python script or something.

**Comment by madhatter88** [comment]
time to spin up a VM, or log on to my Windows machine. Anyways, I am gonna keep cracking at it.

**Comment by madhatter88** [comment]
How much did you copy over from target.bin?

**Comment by madhatter88** [comment]
interesting problem, when i copy over the new UF2 file. it reboots and of course i have to hold the bottom left button again. however my old UF2 file that I replaced (and deleted) is still there. no idea why this is happening.

**Comment by duk-37** [comment]
> 
> 
> How much did you copy over from target.bin?

Assuming you've set it up correctly, all of it.

> 
> 
> interesting problem, when i copy over the new UF2 file. it reboots and of course i have to hold the bottom left button again. however my old UF2 file that I replaced (and deleted) is still there. no idea why this is happening.

IIRC the firmware resets itself if you *really* break things.

**Comment by madhatter88** [comment]
i copied the file over correctly (the file length is the same as it was before) is there anyway you can send me your bin file and .UF2 file?

**Comment by duk-37** [comment]
> 
> 
> i copied the file over correctly (the file length is the same as it was before) is there anyway you can send me your bin file and .UF2 file?

I don't have them on this computer at the moment, but again, you can use [this fork](https://github.com/Monstriu/music-on-dc29-badge) that has a Makefile to generate them for you.

**Comment by madhatter88** [comment]
after you flash it over, do you have to hold any of the buttons down to get it in the mode to play music?

**Comment by duk-37** [comment]
> after you flash it over, do you have to hold any of the buttons down to get it in the mode to play music?

Just pressing the top-left button should work.

**Comment by madhatter88** [comment]
I just tried your steps again and ..... IT WORKS!
